### ISSUE TITLE
helm no longer uses ido-make-buffer-list

### ISSUE THREAD

**Issue by kaz-yos** [wamei/elscreen-separate-buffer-list#8]
helm stopped using `ido-make-buffer-list` in `helm-buffer-list`.

https://github.com/emacs-helm/helm/commit/f7fa3a9e

So the elscreen-specific buffer filtering is lost in the helm versions beyond this commit.

I will post a fix if I can come up with one.

**Comment by kaz-yos** [comment]
My quick fix is the following:

```lisp
(defun my-esbl-buffer-name-filter (buffer-names)
  (let ((buffer-names-to-keep (mapcar #'buffer-name
                                      esbl-separate-buffer-list)))
    (seq-filter (lambda (elt)
                  (member elt buffer-names-to-keep))
                buffer-names)))

(advice-add 'helm-buffer-list
            :filter-return #'my-esbl-buffer-name-filter)
```

This advice just filters the output of `helm-buffer-list` by checking against the `esbl-separate-buffer-list`, the list of buffers that belongs to the current elscreen.

**Comment by wamei** [comment]
https://github.com/wamei/elscreen-separate-buffer-list/commit/88d8850108947949431425a2d938a09d941454e8
